services:
  spring-start:
    build: ./
    depends_on:
      - pgdb
    ports:
      - 8080:8080
    container_name: spring_server


  pgdb:
    image: postgres:15
    restart: always
    ports:
      - 5433:5432
    environment:
      - POSTGRES_DB=shop
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: pgdb
    volumes:
      - pgdbdata:/var/lib/postgresql/data

  redis:
    image: redis:7.2.4
    restart: always
    ports:
      - 6333:6379
    environment:
      - REDIS_PASSWORD=redispassword
      - REDIS_PORT=6379
      - REDIS_DATABASES=4
volumes:
  pgdbdata: null
  server: null
